### ISSUE TITLE
In software mode the HD HUD has incorrect colors

### ISSUE THREAD

**Issue by kandriod** [Aleph-One-Marathon/alephone#118]
![image](https://user-images.githubusercontent.com/25878306/47629876-f280b300-dafa-11e8-8874-67a4ac3f0afc.png)
The shield and air bars are both grey and even with 2 or 3 times overshields shield remains grey. This issue is on 2015 and 1.3b2 for marathon 2 and infinity HD HUDs, the marathon 1 HD HUD is correct.

**Comment by orbea** [comment]
I can reproduce this too.

**Comment by Hopper262** [comment]
This bug has actually been there since the enhanced HUD was introduced. The images are the original original Xbox assets from Freeverse, and to save space in the download, they used real-time tinting to color the 2 bars. We did the same due to time constraints, but color tinting was not available in the software mode HUD engine. As you noticed, the M1 HUD wasn't affected, as it was drawn from scratch specifically for Aleph One.

For years I didn't know if anyone ever tried this combination, but now that it's reported I'll add pre-tinted images so the software HUD looks as intended. Thanks to you both for the reports and testing, it's very helpful!

**Comment by orbea** [comment]
Thanks! I can confirm the new data does not have this issue.
