### ISSUE TITLE
Instant quit when pressing ESC or Start

### ISSUE THREAD

**Issue by kandriod** [Aleph-One-Marathon/alephone#131]
When you press the Escape or Start button in gameplay it's supposed to pause and give you an option to stop playing, however it will often skip the prompt and quit which can have devastating conscequences if the player is far into a segment and doesnt know about alt + p to safely and consistently pause.

**Comment by treellama** [comment]
You can quit without a prompt within the first five seconds after starting the game or using a pattern buffer. After that, it should issue a prompt, and it appears to be doing so when I test it.

Are you waiting five seconds before tapping escape?

**Comment by kandriod** [comment]
Yes, this has happened multiple times while letting time pass after a pattern buffer.

**Comment by treellama** [comment]
I haven't seen it happen yet in Linux, but I haven't spent a lot of time playing. Can you list your OS/system setup? Also, if you can observe a pattern as to when it happens, that would help. A mac OS quit event will also bypass the prompt, if you're using a Mac. Otherwise, I don't see how that prompt would be getting skipped if five or more seconds have elapsed.

**Comment by kandriod** [comment]
It's on windows 7 professional and there's seemingly no pattern to when it skips the prompt.
