### ISSUE TITLE
screen flashes black when switching weapons

### ISSUE THREAD

**Issue by treellama** [Aleph-One-Marathon/alephone#136]
With the weapons-in-hand rendering in 9496db1, the screen flashes black when switching weapons, when the following are true:

1. Bloom is off
2. The brightness is set to "Dark"
3. Replacement textures are not in use

Forcing the gamma shader to be used fixes it, but I haven't narrowed down whether it's a bug with the gamma shader or an OpenGL error in the WiH rendering is shutting down the rendering.

**Comment by TrajansRow** [comment]
I have an idea about why this was happening. The FBO draw operation is not programmable by default; it just binds a texture and uses glDrawArrays to put it on the screen. If a shader is enabled, such as gamma adjustment, the shader will override that behavior. The issue described occurs when an unrelated shader becomes enabled while drawing the sprite layer, but not disabled before the frame buffer is drawn to the screen.

My guess is that the real bug is in RenderRasterize_Shader::render_viewer_sprite, where it calls something to enable a shader but sometimes returns without disabling it. I'm not inclined to do anything about that because a catch-all disable in RenderRasterize_Shader::render_viewer_sprite_layer seems to fix this issue without any additional logic.
