### ISSUE TITLE
Lua does not have access to the player's head direction (for glancing)

### ISSUE THREAD

**Issue by wrkncacnter7** [Aleph-One-Marathon/alephone#149]
If you open up in game info with F10, you can see the yaw update as you glance.  If you print the player's yaw value with lua, the value never changes while glancing.

**Comment by Hopper262** [comment]
A player has two yaw values: one for the legs and one for the head/torso. Lua's Player.direction reports the legs value (which direction you will run by pressing the forward key). Player.monster.facing reports the same value. The head direction does not appear to be available through Lua, which seems like an oversight.

F10 reports the camera's position and direction rather than the player's. You can see this clearly in third-person mode (F6), where the X and Y values will change as you turn.

**Comment by wrkncacnter7** [comment]
That makes sense.  I changed the title.
