### ISSUE TITLE
First left mouse button input not recognized

### ISSUE THREAD

**Issue by ccallahan** [Aleph-One-Marathon/alephone#150]
When you make your first left click input after loading a save from the main menu, the game does not recognize it. This bug exists in the 1.3b2 official release on GitHub and in the latest nightly builds for [Windows](https://bamboo.chancecallahan.com/browse/A1-RASPI-3), [Linux](https://bamboo.chancecallahan.com/browse/A1-LIN-11), and [ARMHF](https://bamboo.chancecallahan.com/browse/A1-RASPI-3) so it is suspected to be in all versions of A1 between those releases. This has been confirmed on the M2 and MInf scenarios, so we suspect it is also an issue in all scenarios.

Games: Marathon 1 (Suspected), Marathon 2, Marathon: Infinity
Build: 1.3b2-github, nightly (3938d2c3)
Confirmed OSs: Windows 10, Linux (ARMHF)

**Comment by ccallahan** [comment]
Pinging @tbcr

**Comment by tbcr** [comment]
Since I know the inquiry of why there are nightly builds being made for A1 is going to be asked; Since we were informed by others that it was a bit of a headache to manage them, we (read: The speedrun people) decided to setup a continuous integration app and a bugtracker to sift through the bugs before sending them this way.  More information regarding that can be found [at this link](https://marathonruns.net/forum/viewtopic.php?f=24&t=8)
----------------------------------
In regards to the particular issue, it was irritating me during practice for Games Done Quick submissions so much that we decided perform a top level troubleshoot, running various version to determine what was experiencing the issue. An educated guess would say that the application is having a snag in regards to SDL input.

**Comment by treellama** [comment]
I created a saved game in Waterloo Waterpark, quit the app, restarted it, loaded the save, and the first click activated my right fist. I tried loading the save both with and without touching the mouse.

Can you give detailed instructions on how to reproduce this?

**Comment by tbcr** [comment]
In regards to how it occurred to me, I was just playing the game like normal on the particular nightly build. I'll setup a input display overlay on OBS when I get home so I can show the input when recording.

In regards to the issue you have referenced, you're latest comment for it is very similar to what was going on for me.

**Comment by treellama** [comment]
I haven't been able to reproduce it "playing like normal" which is why I was asked for more details. The bug description makes it seem like it happens every time, so I was hoping this would be easier to fix than #134. I certainly don't need or want to watch a video, just a description of how to reproduce would help.

**Comment by tbcr** [comment]
I did noticed that when I saved the game, either took a death or reloaded a save game it would occur. In terms of Marathon Infinity, I would noticed the bug around either Foe Hammer, Hang Brain or By Committee on Total Carnage, since those are levels I tend to take a lot of deaths in. I can check to see if the issue occurs before encountering a second/third chapter screen \ taking a death as well.

**Comment by tbcr** [comment]
To preface, the following text regards windows builds. I will later on test on my Manjaro setup.

Ok, booting Marathon Infinity on the latest successfully compiled windows nightly build (2/27/2019); I started the game fresh into the first map and proceed to head to the save terminal near the secret developers switch. After saving and reloading the save state, the game proceeds to then not recognize the first mouse button input.

In addition, booting into Marathon 1 on the official 1.3b2 Windows release, heading into Arrival to the very first save terminal encountered in the game. Upon doing the same process above, first mouse button input was also not recognized.

**Comment by treellama** [comment]
I was able to reproduce this in 1.3b2 for Windows, by selecting "Raw Input". With control set to "OS input" the left button works correctly the first time. Can you confirm this?

**Comment by treellama** [comment]
(I cannot get it to happen in Linux at all, though)

**Comment by ccallahan** [comment]
I can confirm that the issue is present with raw input on M2 using the 1.3b2 on here and from build [#7](https://bamboo.chancecallahan.com/browse/A1-XCMP-7) on our CI. Using OS input fixes it on both builds as well.

**Comment by wrkncacnter7** [comment]
This used to happen to me on linux every single time.  One day it just stopped happening and I haven't been able to reproduce since.

**Comment by Hopper262** [comment]
On my Windows 10 machine, I need to use Raw Input, and I also need to click the save game instead of loading it by pressing Enter. If I use the keyboard for the load, the first click works.

**Comment by Hopper262** [comment]
I wasn't able to reproduce under Linux either, not even using the FC29 binary linked in the first post. The above commit fixes what I was seeing under Windows.
