### ISSUE TITLE
restoring saved games with embedded MML dynamic limits can fail

### ISSUE THREAD

**Issue by treellama** [Aleph-One-Marathon/alephone#201]
If the dynamic limits raise something that is present in the saved game (in this case, the monster limit, and there are more monsters than the default limits in the saved game) it will fail, because the script isn't run until after the monsters are loaded.

Monsters loaded: process_map_wad
Dynamic limits applied: RunLevelScript

**Comment by computersarewitchcraft** [comment]
Save games fail even if the dynamic limits are raised in global MML (ie marathoninfinity.mml). Restoring save games by pressing tab on death works as does quitting to main menu and using continue save game _so long as the player hasn't quit Aleph One since starting a new game on the map._ Save games from a previous session can be restored successfully by first starting a new game on the map in the current session, then quitting to main menu.
