### ISSUE TITLE
Compressed DDS wall textures look wrong with infravision

### ISSUE THREAD

**Issue by wrkncacnter7** [Aleph-One-Marathon/alephone#232]
The blue/purple spots on the walls and floors in this screenshot are not supposed to be there. Using PNG or uncompressed DDS does not have this problem.

![APlagueofDemons_0000](https://user-images.githubusercontent.com/20880967/101712655-3d4bb380-3a53-11eb-882a-2abf14aec13d.png)

**Comment by aaronfreed** [comment]
Apparently using a shader for infravision would both fix this problem, improve load times, and improve memory usage. The only major problem with this solution is that it would require someone to write one. I would heavily encourage this if possible.

I've had this issue as well after typing in `Players[0].infravision_duration=32767` while texturing levels (sometimes infravision helps with texturing dark levels), but I never reported it because we only use infravision in about five levels across the four different scenarios I've mapped for, and I don't think it affected any of the textures in those levels. I never worked out what causes it. Something about some of the DDS compression that Aleph One just doesn't like, I guess.
