### ISSUE TITLE
Stats plugin causes OOS in older films 

### ISSUE THREAD

**Issue by Sharkie-Lino** [Aleph-One-Marathon/alephone#256]
Took the time to examine this carefully, and it seems having the Stats plugin enabled is causing respawn issues in older replays, before some time in 2014 it looks like. What seems to happen most of the time is, the first person to die, they respawn at a different location than where they normally would be, and that obviously causes the out of sync condition. If it is not the first person, then it still soon happens to someone else. None of the replays had any netscripts enabled; all vanilla EMFH. 

I looked at many replays I have from 2012, 2013, and one from January 2014 that has this happen. On the flip side, I have a replay from October of 2014, and the issue is not there, nor is it in replays after that one (at least the ones that I checked, and it was quite a few). I'm guessing maybe this happens in films that were recorded before the Stats plugin was created, which if I remember correctly was introduced in 2014? Or maybe a new A1 had happened then? I can't recall.  

The immediate fix of course is to disable the plugin, then all the films work correctly with no problems. Unsure if that is THE fix, or if there is something more involved. 

This happens on the Mac version of both 1.3.1 (All-in-one) and the A1 1.4 Preview 2 version. Using Mojave. 

Side note: I did mention to TL that I believe the Natures Peace plugin causes something similar to happen, but last time I ever tested that was back in 2013, and he had said (I think, not 100% certain) I shouldn't have that enabled anyway when viewing replays. I forget his reason(s) as to why though. Uncertain if that same thing applies here.

**Comment by treellama** [comment]
Aleph One 1.0.x had a bug where enabling a Lua script (even a read-only one like Stats.lua) would change the random seed. So any films you recorded with Aleph One 1.0.x will need to exactly match the Lua stats on/off in which they were recorded in order to play back correctly.

Aleph One 1.1 fixed this issue in 2014, but added a film compatibility setting to continue the Aleph One 1.0 behavior when playing back old films--otherwise there would be no way to play them back if they WERE recorded with a Lua script enabled.

So, there is no fix for this other than to play very old films back with the exact Lua configuration they were recorded.
