### ISSUE TITLE
Water not being interpolated

### ISSUE THREAD

**Issue by Q3BFG10K** [Aleph-One-Marathon/alephone#270]
Load the Marathon 2 save and activate the switch with the fusion pistol. As the water drops you'll see it looks a jerky 30 FPS.

[1618400193.zip](https://github.com/Aleph-One-Marathon/alephone/files/6310563/1618400193.zip)

**Comment by aaronfreed** [comment]
I didn’t load the saved game, but if this is “Kill Your Television”, it's updating much less often than 30 fps, and it always did. The liquid uses the “smooth” light transition, which is based on trig tables... which (IIRC) only have 512 entries. That means the “smooth” light transition, if used over a long enough time period (say, twenty-four seconds, as on KYT), isn’t smooth at all; it’s updating a _lot_ less often than 30 times a second. (It might be 10⅔ times a second, but I’m making assumptions about how this part of the code works without having actually read it, so don’t put too much stock in that estimate.) The light could be interpolated more smoothly now, but doing so would give players a misleading impression of where the water actually is in the game world, so the Aleph One developers (wisely, IMO) decided not to do that.

Anyhow, I wouldn’t expect anything that isn’t smooth in the original game to be smooth in interpolation. The drone and juggernaut contrails aren’t interpolated either, because they likewise never updated at 30 fps.

**Comment by Q3BFG10K** [comment]
Yes, KYT is the level. If that's the reason then this can be closed. I reported it because I thought they'd missed that case for handling interpolation.

**Comment by treellama** [comment]
Water and light states aren't interpolated, but on KYT they wouldn't be anyway.
