### ISSUE TITLE
Weird rendering glitch when looking down non-transparent wall

### ISSUE THREAD

**Issue by aaronfreed** [Aleph-One-Marathon/alephone#290]
There are certain cases where setting a wall as non-transparent can cause a HOM effect. In this case I’ve got the HOM section showing up black to make it more obvious what the affected region is:

![image](https://user-images.githubusercontent.com/8217916/123492279-187dee80-d5e7-11eb-9853-8b6f27bb3435.png)

Here’s the area in Weland; I had the lines above and below the selected polygon set to non-transparent:

![image](https://user-images.githubusercontent.com/8217916/123492389-524ef500-d5e7-11eb-9ea9-ae894e287f00.png)

I’m fairly sure this occurs because the engine doesn’t quite understand what areas beyond the offending line are supposed to be visible. When I set the line to transparent, the HOM glitch goes away.

![image](https://user-images.githubusercontent.com/8217916/123492416-6f83c380-d5e7-11eb-91e7-50c496f9fa13.png)

We had this issue on one of khfiva’s WMAiD maps as well. I feel like this can _probably_ be fixed without breaking other engine behaviours. _Probably._

**Comment by LidMop** [comment]
I can 90% solve this glitch by making `build_clipping_windows()` sort endpoint-clips more accurately by comparing their clip vectors instead of their (integral, and therefore lossy) x-coordinates. But the glitch will still occur if the view origin is collinear with the opaque side (or extremely close to collinear). I believe this is because even the clip vectors have a small rounding error from their world-to-eye-space transformation, whereas vis-tree ray-casting calculations are done in world space and have zero error. I'm investigating how much trouble it would be to make `build_clipping_windows()` compare endpoint clips by their world-space points and therefore sort them perfectly... this would require storing world-space points in `endpoint_clip_data` or something similar.

**Comment by treellama** [comment]
It's a pretty pathological case to be looking head-on at an opaque line, IMO. Not worth a major change to the code.
