### ISSUE TITLE
Chip insertion eating chips without effect

### ISSUE THREAD

**Issue by aaronfreed** [Aleph-One-Marathon/alephone#385]
Someone reported a bug in a particular level (that has already been fixed for an upcoming patch) on my channel, and it occurred to me that in several cases, the game consumes a chip without actually doing anything. The issue is this: You have a chip slot that controls a tag, which we’ll dub 7, which in turn controls platform 69 (nice), which activates only once. However, if somehow the player is able to activate platform 69 before inserting the chip into the chip insertion point, it won’t be possible to activate tag 7. The result is that the chip insertion point consumes a chip, the tag doesn’t activate, the repair flag isn’t marked, and the player can’t leave the level.

*None* of this strikes me as desirable behaviour, and while yes, it’s arguably on the mapmaker to avoid, none of it is intuitive or, as far as I can tell, had been documented anywhere until I started writing my mapping guides (if it had been, it hadn’t come up in decades, and I can’t find any references to the problem in the Forge manual/Hastur’s Workshop/Battle Cat’s Litterbox/etc.).

So, is there any reason that this shouldn’t be fixed to… some less terrible behaviour? I guess you’d desync films that… experienced the bug and were soft locked anyway? I wouldn’t even think this would require a new film profile because really, who cares.

Tag switches have some other less than optimal behaviour when combined with repair flags, but we’ll start here because it’s the most egregious.

I’ve posted a demo map to demonstrate this. If you open the door, the chip insertion slot will eat your chip without activating the tag and you’ll be soft locked, unable to leave the level. The only way to leave is to insert the chip without opening the door first.

[stupad chip demo.zip](https://github.com/Aleph-One-Marathon/alephone/files/9892966/stupad.chip.demo.zip)

**Comment by SolraBizna** [comment]
I think fixing this behavior should be okay. There are a whole constellation of small ways that tag switches behave much more strangely than a mapmaker might assume, and we can probably fix all of them. We should still put the fix(es) behind a film profile gate to keep film compatibility, because that's no effort at all. I don't know a lot about current scenarios, but based on the descriptions I've heard of the weirdnesses, not even an insane mapmaker would *deliberately* take advantage of any of them.

**Comment by SolraBizna** [comment]
```patch
diff --git a/Source_Files/GameWorld/devices.cpp b/Source_Files/GameWorld/devices.cpp
index 2b48d609..e8750b29 100644
--- a/Source_Files/GameWorld/devices.cpp
+++ b/Source_Files/GameWorld/devices.cpp
@@ -503,6 +503,8 @@ void try_and_toggle_control_panel(
                                                make_sound= set_tagged_light_statuses(side->control_panel_permutation, state);
                                                if (try_and_change_tagged_platform_states(side->control_panel_permutation, state)) make_sound= true;
                                                if (!side->control_panel_permutation) make_sound= true;
+                                               // If we eat the chip, we must flip. -SB
+                                               if (definition->item != NONE) make_sound= true;
                                                if (make_sound)
                                                {
                                                        SET_CONTROL_PANEL_STATUS(side, state);
```

This change should make it so that a tag switch that has just eaten a chip will change state, even when there is no underlying platform or light that changed state. The alternative fix would be to somehow prevent the chip from being eaten iff it would not change any platforms or lights, which would be a complicated, intrusive change.

This change does not affect non-item-consuming panels. Regular tag switches and destructible panels will behave exactly as before.

I would recommend gating this change behind a film profile bump, but it could easily be argued that no scenario has the infinite pointless chip eating as an intended behavior, and therefore that a film profile bump is not needed.

I'm not in a position to test this change.
