### ISSUE TITLE
Match mouse vertical and horizontal sensitivity

### ISSUE THREAD

**Issue by tauin** [Aleph-One-Marathon/alephone#391]
One of the most disorienting things about this game is the strange mouse controls, despite being set at the same sentivity in the game settings horizontal sensitivity is noticiably more "sluggish" than vertical movement, its like its being pulled through tar, not sure why though.

**Comment by treellama** [comment]
These should match if you are set to "Modern" mouse feel and have the sensitivity sliders set to the same number.

If you have the speed turned up you may be running into the turn speed limit, which you can remove by editing the [preferences file](https://github.com/Aleph-One-Marathon/alephone/wiki/File-Locations#preferences) in a text editor and searching for `classic_aim_speed_limits`. Change it to false instead of true
