### ISSUE TITLE
(v1.2.1) (OpenGL Shader) Marathon 2: level "What About Bob?" texture flickering

### ISSUE THREAD

**Issue by Zetren** [Aleph-One-Marathon/alephone#40]
One texture immediately flickers above the player 180 degrees from the starting position.

http://puu.sh/quy0s/c6d63c2ca6.jpg
http://puu.sh/quy01/abbf50d331.jpg

**Comment by SolraBizna** [comment]
I and two of my friends confirm this bug. Testing shows that this bug only occurs under the Shader renderer; the Classic (with and without Z Buffer enabled) and Software renderers do not exhibit this bug.

**Comment by aaronfreed** [comment]
I realise I’m like four years late with this, but this it might be helpful to add that this seems to be occurring because there are several split polygons in “What About Bob?” with ceiling heights that are lower than their floor heights. This occurs on at least one polygon in “Hang Brain” too, I believe.
