### ISSUE TITLE
M2 Lua HUD elements misaligned.

### ISSUE THREAD

**Issue by OpenRift412** [Aleph-One-Marathon/alephone#407]
I noticed some subtle differences between the built-in M2 HUD and the lua version of it (aside from the font scaling). The bars at the bottom, the motion sensor, as well as the green weapon sprites don't align properly like they do in the base HUD.

Native HUD: 
![image](https://user-images.githubusercontent.com/29780788/222242203-1626c737-fc17-49ec-9f39-82da63923bde.png)

Lua HUD: 
![image](https://user-images.githubusercontent.com/29780788/222242254-87c6fbc1-95af-4b2e-aaf5-62e326f54476.png)

**Comment by tst2005** [comment]
The difference is not easy to see :  I opened the both image in separate tab and quickly switch between them.
The wrong offset seems 1 pixel up, 1 pixel left for the motion sensor. same for the red bar.
My comment is just to confirm your nice catch !

**Comment by OpenRift412** [comment]
Something I'd also like to note is that when running at 640x480, it seems to fix itself.

**Comment by Hopper262** [comment]
Thanks for your report! I did some extra testing, and as far as I can tell, neither the plugin nor Aleph One are doing anything wrong, but image-scaling artifacts prevent Lua drawing from being pixel-accurate to the built-in code in all situations.

There are three requirements for misalignment:

* Rendering System is Software
* HUD Size is Largest
* Screen Size height isn't a multiple of 480

In the built-in HUD for the software renderer, the HUD is assembled at its original 640x160 size, and scaled up at the very end. Lua HUDs always draw at full screen resolution, so each element is positioned and scaled individually. (That's why the font scales in the original but not in the Lua HUD.) The upscaling library used by Aleph One will shift certain parts of an image more than others, so the individually-scaled images accumulate different artifacts.

In your example image, where the HUD is scaled up to about 5.5x the original, a single pixel from the original shape can be anywhere from 4 to 7 screen pixels tall or wide. The left edge of the motion sensor overlay is supposed to align with the 17th column of background image pixels, but because of the scaling algorithm, that column can end up several screen pixels away from its ideal location. The pattern of which pixels are bigger and which are smaller also won't line up between two overlaid images.

If you're building a new HUD with custom graphics, these discrepancies can be minimized by having the top and/or left corners line up. For instance, export each Photoshop layer at the full HUD size, leaving transparent areas in the overlaid PNGs instead of cropping them out. That also makes the Lua code easier to write, since you don't have to change x and y offsets if you redesign an element.
