### ISSUE TITLE
(v1.3a1) (OpenGL Shader) Marathon Infinity: level "Rise Robot Rise" hall of mirrors glitch

### ISSUE THREAD

**Issue by Zetren** [Aleph-One-Marathon/alephone#41]
In the secret room at the top-right corner of the map there is said glitch when looking out of the right window. located [here](http://images.akamai.steamusercontent.com/ugc/263844677735747707/A73AB3FC404B8B2431ACED5565956A40D20F1180/)

Pics of glitch: 
http://images.akamai.steamusercontent.com/ugc/263844677735747015/D71CAA656006775E1E4104FCD0CBEA299774E459/

http://images.akamai.steamusercontent.com/ugc/263844677735746430/402FA08E4BF5C9D09D47213FF2546A3D3FDD782B/

**Comment by SolraBizna** [comment]
When I examine the area in Forge I do not see any unrendered space. When I examine that area in Aleph One with the Classic renderer I see something very similar to that screenshot; it looks to me like part of the space landscape texture being drawn with the Normal transfer mode. In Forge (and in A1 with the Software renderer), the ceiling in question just appears mysteriously black, regardless of light brightness.

My theory is that the ceiling there somehow lost its transfer mode, possibly due to a bug in an early version of Forge. (If I had a usable option key, or a modern map editing tool, I could test this theory...) If this is the case, the true bug is that there's an inconsistency between the Software and OpenGL renderers when it comes to rendering landscape textures with non-Landscape transfer mode.

**Comment by TheFakeMontyOnTheRun** [comment]
I've just seen this on the bottom of a plasma(?) pool in Begging For Mercy Makes Me Angry, using software rendering.
![mirrors](https://user-images.githubusercontent.com/2441483/30184191-17ae242e-9415-11e7-8e0b-f52b37e16dea.png)

"Works as intended"?
