### ISSUE TITLE
Terminal cannot scroll backwards to any page that is a centered, full-width image

### ISSUE THREAD

**Issue by baudrillardboy** [Aleph-One-Marathon/alephone#438]
Not sure if it's related to being full-width or centered. It does not affect scrolling forwards or backwards for later pages.

For example, if Page 4/10 is a full-width, centered image, Pages 1–4 will be inaccessible once the player scrolls to Page 5 (unless they exit the terminal and log back on). Pages 5–10 will behave normally.

**Comment by treellama** [comment]
Here is a map that demonstrates the problem: 
[Issue438.zip](https://github.com/Aleph-One-Marathon/alephone/files/12566992/Issue438.zip)

**Comment by treellama** [comment]
This happens because `count_total_lines` returns 0 for full-width PICTs, causing `if(terminal->current_line>=terminal->maximum_line)` to return true at computer_interface.cpp:2019.

The fix is to check for a 0 maximum line count at computer_interface.cpp:1734 and set it to 1 instead. Unfortunately this will break film compatibility.
