### ISSUE TITLE
Marathon 1 Habe Quiddam flooded platform doesn't flood

### ISSUE THREAD

**Issue by zeamador** [Aleph-One-Marathon/alephone#69]
In M1, the platform on Habe Quiddam that descends into lava next to the alien device is marked submergeable and becomes lava when at its minimum. In M1A1 it stays dry. I can provide pictures if it's unclear what I'm talking about. It looks like this feature has been implemented since [this commit in 2013](https://github.com/Aleph-One-Marathon/alephone/commit/53bb75f53efcb23abc504b55253307009a0f398b) so it should work correctly.

**Comment by Hopper262** [comment]
Nice catch! I believe the large platform stays dry because it's not directly touching the lava, but is only touching another flooded platform (the one which originally formed the windowsill). The `find_flooding_polygon` routine fails to account for this case.

This gameplay-affecting bug will require a new film profile, which for various reasons I'd like to avoid in the next release, so the fix may be delayed a bit. Sorry for the inconvenience.
