### ISSUE TITLE
Gamepad swimming in Durandal and infinity

### ISSUE THREAD

**Issue by kandriod** [Aleph-One-Marathon/alephone#70]
The controls don't work properly with a gamepad in M2 and MI, even if you leave "always swim" off in preferences you will always swim while moving forward and don't swim when moving backward, also the swim button doesn't do anything, even if you set swim to a key.

**Comment by LidMop** [comment]
I know the root cause of this! Whenever a controller input axis mapped to "forward velocity" is nonzero, the game will use `_absolute_position_mode` and stuff an encoded throttle value in the 7-bit, poorly-named "absolute position" field of action flags. The problem is that this field overlaps/clobbers `_run_dont_walk_bit` (which controls swimming as well as running). Whether this bit is set or cleared on any given frame depends on the throttle! For example, at full backward throttle, the encoded throttle value is 0, and therefore `_run_dont_walk_bit` is clear. At full forward throttle, the encoded throttle value is 127, and therefore `_run_dont_walk_bit` is set.

While this defect was inherited from the original Bungie M2 source release, I think that `_absolute_position_mode` was simply an incomplete feature and never actually used until Aleph One added controller support in 2009 (ad77afca9e9103d234d4b890aff2b1037759338e) and made use of `_absolute_position_mode` without realizing the defect. The original M∞ _did_ support controllers via InputSprocket on PPC but I'm like 70% confident that `_absolute_position_mode` wasn't used, even in v1.5 (I'm having trouble confirming this because we only have the M∞ v1.1 source release and I'm having trouble getting InputSprocket to work properly under the SheepShaver PPC emulator so that I can see whether v1.5 supports any kind of variable-speed control that would indicate the use of `_absolute_position_mode`).

I see 2 possible solutions:
1. Avoid using `_absolute_position_mode` and reimplement variable-speed foreward velocity so that it works the same way as variable-speed sidestepping (pulse-width modulation). I have tested this, but it looked ugly (screen jittering) at less-than-full throttle values, especially if "Camera Bobbing" is enabled. The upside is that there is no compatibility impact.
2. Change the semantics of action flags so that the bit currently named `_swim_bit` means running/swimming and remove that meaning from the bit currently named `_run_dont_walk_bit`. This would require a new film profile and break netplay compatibility with previous versions. If we go this route, we should also take the opportunity to fix the [buggy forward throttle scaling](https://github.com/Aleph-One-Marathon/alephone/blob/1a9888a18b76f39e7092c1afc634e53268c464c6/Source_Files/GameWorld/physics.cpp#L666) so that the max decoded throttle value of 63, not 64, corresponds to `maximum_forward_velocity`. We should also limit the acceleration and deceleration to the physics model constants so that the physics model isn't violated.

I'm currently investigating making massive changes to action flags that would effectively include Solution 2 above, as well as adding similar throttle support for sidestepping, as part of a larger effort to increase yaw/pitch resolution. I feel that work is 3-10 months away from reaching the pull-request stage.

**Comment by Hopper262** [comment]
A third solution would be to mask out the run/swim bit while encoding input flags, so it does not get overwritten. This might be pretty bad control-wise, as the bit is fairly significant, and without a new film profile it will still get treated as part of the velocity.

Not having tested yet, I'm not sure whether solution 1 or 3 is less terrible, but as it stands the controller is pretty useless for M2/MI single-player. The upcoming release finally supports other unfinished parts of the gamepad experience (main menu, terminals, chapter screens), so I definitely want to get a net-compatible stopgap fix in there.

**Comment by Hopper262** [comment]
Version 1.3b1 fixes this, by ripping out variable-speed movement altogether. This avoids the swimming bug. 1.3b1 includes several other controller improvements; I'd appreciate any feedback you have on playing with a gamepad now.

**Comment by kandriod** [comment]
I do have a request for gamepad, Games such as Halo and killzone 3, and the xbox 360 version of marathon 2 have aim acceleration which makes both precise aim and fast turning possible at the same time, though it's not a deal breaker to lack it I think it would improve the gamepad experience to implement this in aleph one.

**Comment by Hopper262** [comment]
You can get a simple version of aim acceleration if you switch "Controller Aiming" to "Treat as Buttons". It will accelerate the longer you hold a direction, just like the keyboard aiming does. I prefer this mode, although the max speed may be too low for your liking, and it no longer moves more slowly if you press the stick lightly.

Aim acceleration in analog mode will probably not make it into 1.3, but it is a good idea so hopefully we can get it added eventually.
