### ISSUE TITLE
M1 Enforcer rifle desyncs online

### ISSUE THREAD

**Issue by kandriod** [Aleph-One-Marathon/alephone#79]
If you fire the alien weapon/Enforcer rifle online in either VS or co op the game will desync without fail.

**Comment by ravenshining** [comment]
What difficulty level were you playing on?  I saw a blue enforcer, so you're not on TC, but could be on Major Damage.

Projectiles in Marathon are conventionally limited to a speed of 1024 (or 1 WU/tick) supposedly in order to prevent sync issues.  If you set projectile speed high enough, it will behave inconsistently even in single player, failing to collide with objects in it's path. I believe the M1 alien weapon fires the only shots in Marathon to both travel at a speed of 1024 AND be marked as "alien."  Alien shots get sped up or slowed down based on difficulty level, like so:

Normal: 1024, 1 WU/tick
Major Damage: 1152, 1 1/8 WU/tick
Total Carnage: 1280, 1 1/4 WU/tick

Since your desync is happening specifically after firing the M1 Alien Weapon, maybe try several games with different difficulty levels on the same connection and see if that replicates your issue along difficulty lines.

**Comment by treellama** [comment]
This happens without co-op Lua enabled as well

**Comment by treellama** [comment]
Verified with 47ca540 and up to date data files, this appears to stay in sync
